name: Build and Release Stay_Awake

on:
  release:
    types: [created]
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Required for uploading release assets

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  # Use Python 3.12 for better PyInstaller compatibility
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wakepy pystray Pillow pyinstaller
    
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --noconsole --name "Stay_Awake" Stay_Awake.py
    
    - name: Verify executable exists
      run: |
        if (Test-Path "dist\Stay_Awake.exe") {
          Write-Host "✅ Stay_Awake.exe created successfully"
          Get-ChildItem "dist\Stay_Awake.exe" | Format-List Name, Length, LastWriteTime
        } else {
          Write-Host "❌ Stay_Awake.exe not found!"
          exit 1
        }
      shell: powershell
    
    - name: Upload folder-based distribution 
      uses: actions/upload-artifact@v4
      with:
        name: Stay_Awake-Portable
        path: dist/Stay_Awake-Portable.zip
    
    - name: Upload to release (if this was triggered by a release)
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: dist/Stay_Awake-Portable.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Future: Add macOS and Linux builds
  # build-macos:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     # ... similar steps for macOS
  
  # build-linux:
  #   runs-on: ubuntu-latest  
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     # ... similar steps for Linux
